// Copyright (c) Abstract Machines

// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/lestrrat-go/jwx/v2/jwk"
	"github.com/lestrrat-go/jwx/v2/jwt"
	mock "github.com/stretchr/testify/mock"
)

// NewKeyManager creates a new instance of KeyManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeyManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeyManager {
	mock := &KeyManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// KeyManager is an autogenerated mock type for the KeyManager type
type KeyManager struct {
	mock.Mock
}

type KeyManager_Expecter struct {
	mock *mock.Mock
}

func (_m *KeyManager) EXPECT() *KeyManager_Expecter {
	return &KeyManager_Expecter{mock: &_m.Mock}
}

// ParseJWT provides a mock function for the type KeyManager
func (_mock *KeyManager) ParseJWT(token string) (jwt.Token, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ParseJWT")
	}

	var r0 jwt.Token
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (jwt.Token, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) jwt.Token); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jwt.Token)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KeyManager_ParseJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseJWT'
type KeyManager_ParseJWT_Call struct {
	*mock.Call
}

// ParseJWT is a helper method to define mock.On call
//   - token string
func (_e *KeyManager_Expecter) ParseJWT(token interface{}) *KeyManager_ParseJWT_Call {
	return &KeyManager_ParseJWT_Call{Call: _e.mock.On("ParseJWT", token)}
}

func (_c *KeyManager_ParseJWT_Call) Run(run func(token string)) *KeyManager_ParseJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *KeyManager_ParseJWT_Call) Return(token1 jwt.Token, err error) *KeyManager_ParseJWT_Call {
	_c.Call.Return(token1, err)
	return _c
}

func (_c *KeyManager_ParseJWT_Call) RunAndReturn(run func(token string) (jwt.Token, error)) *KeyManager_ParseJWT_Call {
	_c.Call.Return(run)
	return _c
}

// PublicJWKS provides a mock function for the type KeyManager
func (_mock *KeyManager) PublicJWKS() []jwk.Key {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PublicJWKS")
	}

	var r0 []jwk.Key
	if returnFunc, ok := ret.Get(0).(func() []jwk.Key); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]jwk.Key)
		}
	}
	return r0
}

// KeyManager_PublicJWKS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublicJWKS'
type KeyManager_PublicJWKS_Call struct {
	*mock.Call
}

// PublicJWKS is a helper method to define mock.On call
func (_e *KeyManager_Expecter) PublicJWKS() *KeyManager_PublicJWKS_Call {
	return &KeyManager_PublicJWKS_Call{Call: _e.mock.On("PublicJWKS")}
}

func (_c *KeyManager_PublicJWKS_Call) Run(run func()) *KeyManager_PublicJWKS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *KeyManager_PublicJWKS_Call) Return(keys []jwk.Key) *KeyManager_PublicJWKS_Call {
	_c.Call.Return(keys)
	return _c
}

func (_c *KeyManager_PublicJWKS_Call) RunAndReturn(run func() []jwk.Key) *KeyManager_PublicJWKS_Call {
	_c.Call.Return(run)
	return _c
}

// Rotate provides a mock function for the type KeyManager
func (_mock *KeyManager) Rotate(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rotate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// KeyManager_Rotate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rotate'
type KeyManager_Rotate_Call struct {
	*mock.Call
}

// Rotate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *KeyManager_Expecter) Rotate(ctx interface{}) *KeyManager_Rotate_Call {
	return &KeyManager_Rotate_Call{Call: _e.mock.On("Rotate", ctx)}
}

func (_c *KeyManager_Rotate_Call) Run(run func(ctx context.Context)) *KeyManager_Rotate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *KeyManager_Rotate_Call) Return(err error) *KeyManager_Rotate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *KeyManager_Rotate_Call) RunAndReturn(run func(ctx context.Context) error) *KeyManager_Rotate_Call {
	_c.Call.Return(run)
	return _c
}

// SignJWT provides a mock function for the type KeyManager
func (_mock *KeyManager) SignJWT(token jwt.Token) ([]byte, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for SignJWT")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(jwt.Token) ([]byte, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(jwt.Token) []byte); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(jwt.Token) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KeyManager_SignJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignJWT'
type KeyManager_SignJWT_Call struct {
	*mock.Call
}

// SignJWT is a helper method to define mock.On call
//   - token jwt.Token
func (_e *KeyManager_Expecter) SignJWT(token interface{}) *KeyManager_SignJWT_Call {
	return &KeyManager_SignJWT_Call{Call: _e.mock.On("SignJWT", token)}
}

func (_c *KeyManager_SignJWT_Call) Run(run func(token jwt.Token)) *KeyManager_SignJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 jwt.Token
		if args[0] != nil {
			arg0 = args[0].(jwt.Token)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *KeyManager_SignJWT_Call) Return(bytes []byte, err error) *KeyManager_SignJWT_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *KeyManager_SignJWT_Call) RunAndReturn(run func(token jwt.Token) ([]byte, error)) *KeyManager_SignJWT_Call {
	_c.Call.Return(run)
	return _c
}
