// Copyright (c) Abstract Machines

// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/absmach/supermq/auth"

	mock "github.com/stretchr/testify/mock"
)

// KeyRepository is an autogenerated mock type for the KeyRepository type
type KeyRepository struct {
	mock.Mock
}

type KeyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *KeyRepository) EXPECT() *KeyRepository_Expecter {
	return &KeyRepository_Expecter{mock: &_m.Mock}
}

// Remove provides a mock function with given fields: ctx, issuer, id
func (_m *KeyRepository) Remove(ctx context.Context, issuer string, id string) error {
	ret := _m.Called(ctx, issuer, id)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, issuer, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// KeyRepository_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type KeyRepository_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - issuer string
//   - id string
func (_e *KeyRepository_Expecter) Remove(ctx interface{}, issuer interface{}, id interface{}) *KeyRepository_Remove_Call {
	return &KeyRepository_Remove_Call{Call: _e.mock.On("Remove", ctx, issuer, id)}
}

func (_c *KeyRepository_Remove_Call) Run(run func(ctx context.Context, issuer string, id string)) *KeyRepository_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *KeyRepository_Remove_Call) Return(_a0 error) *KeyRepository_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *KeyRepository_Remove_Call) RunAndReturn(run func(context.Context, string, string) error) *KeyRepository_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Retrieve provides a mock function with given fields: ctx, issuer, id
func (_m *KeyRepository) Retrieve(ctx context.Context, issuer string, id string) (auth.Key, error) {
	ret := _m.Called(ctx, issuer, id)

	if len(ret) == 0 {
		panic("no return value specified for Retrieve")
	}

	var r0 auth.Key
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (auth.Key, error)); ok {
		return rf(ctx, issuer, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) auth.Key); ok {
		r0 = rf(ctx, issuer, id)
	} else {
		r0 = ret.Get(0).(auth.Key)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, issuer, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeyRepository_Retrieve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retrieve'
type KeyRepository_Retrieve_Call struct {
	*mock.Call
}

// Retrieve is a helper method to define mock.On call
//   - ctx context.Context
//   - issuer string
//   - id string
func (_e *KeyRepository_Expecter) Retrieve(ctx interface{}, issuer interface{}, id interface{}) *KeyRepository_Retrieve_Call {
	return &KeyRepository_Retrieve_Call{Call: _e.mock.On("Retrieve", ctx, issuer, id)}
}

func (_c *KeyRepository_Retrieve_Call) Run(run func(ctx context.Context, issuer string, id string)) *KeyRepository_Retrieve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *KeyRepository_Retrieve_Call) Return(key auth.Key, err error) *KeyRepository_Retrieve_Call {
	_c.Call.Return(key, err)
	return _c
}

func (_c *KeyRepository_Retrieve_Call) RunAndReturn(run func(context.Context, string, string) (auth.Key, error)) *KeyRepository_Retrieve_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, key
func (_m *KeyRepository) Save(ctx context.Context, key auth.Key) (string, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, auth.Key) (string, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, auth.Key) string); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, auth.Key) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeyRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type KeyRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - key auth.Key
func (_e *KeyRepository_Expecter) Save(ctx interface{}, key interface{}) *KeyRepository_Save_Call {
	return &KeyRepository_Save_Call{Call: _e.mock.On("Save", ctx, key)}
}

func (_c *KeyRepository_Save_Call) Run(run func(ctx context.Context, key auth.Key)) *KeyRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(auth.Key))
	})
	return _c
}

func (_c *KeyRepository_Save_Call) Return(id string, err error) *KeyRepository_Save_Call {
	_c.Call.Return(id, err)
	return _c
}

func (_c *KeyRepository_Save_Call) RunAndReturn(run func(context.Context, auth.Key) (string, error)) *KeyRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewKeyRepository creates a new instance of KeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeyRepository {
	mock := &KeyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
