// Copyright (c) Abstract Machines

// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/absmach/supermq/api/grpc/emails/v1"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewEmailServiceClient creates a new instance of EmailServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailServiceClient {
	mock := &EmailServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EmailServiceClient is an autogenerated mock type for the EmailServiceClient type
type EmailServiceClient struct {
	mock.Mock
}

type EmailServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *EmailServiceClient) EXPECT() *EmailServiceClient_Expecter {
	return &EmailServiceClient_Expecter{mock: &_m.Mock}
}

// SendEmail provides a mock function for the type EmailServiceClient
func (_mock *EmailServiceClient) SendEmail(ctx context.Context, in *v1.EmailReq, opts ...grpc.CallOption) (*v1.SendEmailRes, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 *v1.SendEmailRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.EmailReq, ...grpc.CallOption) (*v1.SendEmailRes, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.EmailReq, ...grpc.CallOption) *v1.SendEmailRes); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.SendEmailRes)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.EmailReq, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EmailServiceClient_SendEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmail'
type EmailServiceClient_SendEmail_Call struct {
	*mock.Call
}

// SendEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.EmailReq
//   - opts ...grpc.CallOption
func (_e *EmailServiceClient_Expecter) SendEmail(ctx interface{}, in interface{}, opts ...interface{}) *EmailServiceClient_SendEmail_Call {
	return &EmailServiceClient_SendEmail_Call{Call: _e.mock.On("SendEmail",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *EmailServiceClient_SendEmail_Call) Run(run func(ctx context.Context, in *v1.EmailReq, opts ...grpc.CallOption)) *EmailServiceClient_SendEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.EmailReq
		if args[1] != nil {
			arg1 = args[1].(*v1.EmailReq)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *EmailServiceClient_SendEmail_Call) Return(sendEmailRes *v1.SendEmailRes, err error) *EmailServiceClient_SendEmail_Call {
	_c.Call.Return(sendEmailRes, err)
	return _c
}

func (_c *EmailServiceClient_SendEmail_Call) RunAndReturn(run func(ctx context.Context, in *v1.EmailReq, opts ...grpc.CallOption) (*v1.SendEmailRes, error)) *EmailServiceClient_SendEmail_Call {
	_c.Call.Return(run)
	return _c
}
