// Copyright (c) Abstract Machines

// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/absmach/supermq/api/grpc/users/v1"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewUsersServiceClient creates a new instance of UsersServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsersServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsersServiceClient {
	mock := &UsersServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UsersServiceClient is an autogenerated mock type for the UsersServiceClient type
type UsersServiceClient struct {
	mock.Mock
}

type UsersServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *UsersServiceClient) EXPECT() *UsersServiceClient_Expecter {
	return &UsersServiceClient_Expecter{mock: &_m.Mock}
}

// SendEmailWithUserId provides a mock function for the type UsersServiceClient
func (_mock *UsersServiceClient) SendEmailWithUserId(ctx context.Context, in *v1.SendEmailWithUserIdReq, opts ...grpc.CallOption) (*v1.SendEmailRes, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SendEmailWithUserId")
	}

	var r0 *v1.SendEmailRes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.SendEmailWithUserIdReq, ...grpc.CallOption) (*v1.SendEmailRes, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.SendEmailWithUserIdReq, ...grpc.CallOption) *v1.SendEmailRes); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.SendEmailRes)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.SendEmailWithUserIdReq, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UsersServiceClient_SendEmailWithUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmailWithUserId'
type UsersServiceClient_SendEmailWithUserId_Call struct {
	*mock.Call
}

// SendEmailWithUserId is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.SendEmailWithUserIdReq
//   - opts ...grpc.CallOption
func (_e *UsersServiceClient_Expecter) SendEmailWithUserId(ctx interface{}, in interface{}, opts ...interface{}) *UsersServiceClient_SendEmailWithUserId_Call {
	return &UsersServiceClient_SendEmailWithUserId_Call{Call: _e.mock.On("SendEmailWithUserId",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *UsersServiceClient_SendEmailWithUserId_Call) Run(run func(ctx context.Context, in *v1.SendEmailWithUserIdReq, opts ...grpc.CallOption)) *UsersServiceClient_SendEmailWithUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.SendEmailWithUserIdReq
		if args[1] != nil {
			arg1 = args[1].(*v1.SendEmailWithUserIdReq)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *UsersServiceClient_SendEmailWithUserId_Call) Return(sendEmailRes *v1.SendEmailRes, err error) *UsersServiceClient_SendEmailWithUserId_Call {
	_c.Call.Return(sendEmailRes, err)
	return _c
}

func (_c *UsersServiceClient_SendEmailWithUserId_Call) RunAndReturn(run func(ctx context.Context, in *v1.SendEmailWithUserIdReq, opts ...grpc.CallOption) (*v1.SendEmailRes, error)) *UsersServiceClient_SendEmailWithUserId_Call {
	_c.Call.Return(run)
	return _c
}
