// Copyright (c) Abstract Machines
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.0
// source: users/v1/users.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendEmailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            []string               `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty"`           // Email recipients
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`       // Sender email address (optional)
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"` // Email subject
	Header        string                 `protobuf:"bytes,4,opt,name=header,proto3" json:"header,omitempty"`   // Email header text
	User          string                 `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`       // User name
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"` // Email content/URL
	Footer        string                 `protobuf:"bytes,7,opt,name=footer,proto3" json:"footer,omitempty"`   // Email footer text
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailReq) Reset() {
	*x = SendEmailReq{}
	mi := &file_users_v1_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailReq) ProtoMessage() {}

func (x *SendEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailReq.ProtoReflect.Descriptor instead.
func (*SendEmailReq) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{0}
}

func (x *SendEmailReq) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *SendEmailReq) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SendEmailReq) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmailReq) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *SendEmailReq) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SendEmailReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendEmailReq) GetFooter() string {
	if x != nil {
		return x.Footer
	}
	return ""
}

type SendEmailRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sent          bool                   `protobuf:"varint,1,opt,name=sent,proto3" json:"sent,omitempty"` // Whether the email was sent successfully
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRes) Reset() {
	*x = SendEmailRes{}
	mi := &file_users_v1_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRes) ProtoMessage() {}

func (x *SendEmailRes) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRes.ProtoReflect.Descriptor instead.
func (*SendEmailRes) Descriptor() ([]byte, []int) {
	return file_users_v1_users_proto_rawDescGZIP(), []int{1}
}

func (x *SendEmailRes) GetSent() bool {
	if x != nil {
		return x.Sent
	}
	return false
}

var File_users_v1_users_proto protoreflect.FileDescriptor

const file_users_v1_users_proto_rawDesc = "" +
	"\n" +
	"\x14users/v1/users.proto\x12\busers.v1\"\xaa\x01\n" +
	"\fSendEmailReq\x12\x0e\n" +
	"\x02to\x18\x01 \x03(\tR\x02to\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x16\n" +
	"\x06header\x18\x04 \x01(\tR\x06header\x12\x12\n" +
	"\x04user\x18\x05 \x01(\tR\x04user\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x16\n" +
	"\x06footer\x18\a \x01(\tR\x06footer\"\"\n" +
	"\fSendEmailRes\x12\x12\n" +
	"\x04sent\x18\x01 \x01(\bR\x04sent2M\n" +
	"\fUsersService\x12=\n" +
	"\tSendEmail\x12\x16.users.v1.SendEmailReq\x1a\x16.users.v1.SendEmailRes\"\x00B.Z,github.com/absmach/supermq/api/grpc/users/v1b\x06proto3"

var (
	file_users_v1_users_proto_rawDescOnce sync.Once
	file_users_v1_users_proto_rawDescData []byte
)

func file_users_v1_users_proto_rawDescGZIP() []byte {
	file_users_v1_users_proto_rawDescOnce.Do(func() {
		file_users_v1_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_v1_users_proto_rawDesc), len(file_users_v1_users_proto_rawDesc)))
	})
	return file_users_v1_users_proto_rawDescData
}

var file_users_v1_users_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_users_v1_users_proto_goTypes = []any{
	(*SendEmailReq)(nil), // 0: users.v1.SendEmailReq
	(*SendEmailRes)(nil), // 1: users.v1.SendEmailRes
}
var file_users_v1_users_proto_depIdxs = []int32{
	0, // 0: users.v1.UsersService.SendEmail:input_type -> users.v1.SendEmailReq
	1, // 1: users.v1.UsersService.SendEmail:output_type -> users.v1.SendEmailRes
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_users_v1_users_proto_init() }
func file_users_v1_users_proto_init() {
	if File_users_v1_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_v1_users_proto_rawDesc), len(file_users_v1_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_v1_users_proto_goTypes,
		DependencyIndexes: file_users_v1_users_proto_depIdxs,
		MessageInfos:      file_users_v1_users_proto_msgTypes,
	}.Build()
	File_users_v1_users_proto = out.File
	file_users_v1_users_proto_goTypes = nil
	file_users_v1_users_proto_depIdxs = nil
}
