// Copyright (c) Abstract Machines
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: emails/v1/emails.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContactType int32

const (
	ContactType_CONTACT_TYPE_UNSPECIFIED ContactType = 0
	ContactType_CONTACT_TYPE_ID          ContactType = 1
	ContactType_CONTACT_TYPE_EMAIL       ContactType = 2
)

// Enum value maps for ContactType.
var (
	ContactType_name = map[int32]string{
		0: "CONTACT_TYPE_UNSPECIFIED",
		1: "CONTACT_TYPE_ID",
		2: "CONTACT_TYPE_EMAIL",
	}
	ContactType_value = map[string]int32{
		"CONTACT_TYPE_UNSPECIFIED": 0,
		"CONTACT_TYPE_ID":          1,
		"CONTACT_TYPE_EMAIL":       2,
	}
)

func (x ContactType) Enum() *ContactType {
	p := new(ContactType)
	*p = x
	return p
}

func (x ContactType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContactType) Descriptor() protoreflect.EnumDescriptor {
	return file_emails_v1_emails_proto_enumTypes[0].Descriptor()
}

func (ContactType) Type() protoreflect.EnumType {
	return &file_emails_v1_emails_proto_enumTypes[0]
}

func (x ContactType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContactType.Descriptor instead.
func (ContactType) EnumDescriptor() ([]byte, []int) {
	return file_emails_v1_emails_proto_rawDescGZIP(), []int{0}
}

type EmailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`                                                                                  // Sender
	FromType      ContactType            `protobuf:"varint,2,opt,name=from_type,json=fromType,proto3,enum=emails.v1.ContactType" json:"from_type,omitempty"`                              // indicate sender id or email
	Tos           []string               `protobuf:"bytes,3,rep,name=tos,proto3" json:"tos,omitempty"`                                                                                    // recipients
	ToType        ContactType            `protobuf:"varint,4,opt,name=to_type,json=toType,proto3,enum=emails.v1.ContactType" json:"to_type,omitempty"`                                    // indicate recipient id or email
	Subject       string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`                                                                            // Email subject
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`                                                                            // Email content/URL
	Template      *string                `protobuf:"bytes,10,opt,name=template,proto3,oneof" json:"template,omitempty"`                                                                   // whole template for emailer
	TemplateFile  *string                `protobuf:"bytes,11,opt,name=template_file,json=templateFile,proto3,oneof" json:"template_file,omitempty"`                                       // template file for emailer
	Options       map[string]string      `protobuf:"bytes,12,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // map for template
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailReq) Reset() {
	*x = EmailReq{}
	mi := &file_emails_v1_emails_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailReq) ProtoMessage() {}

func (x *EmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_emails_v1_emails_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailReq.ProtoReflect.Descriptor instead.
func (*EmailReq) Descriptor() ([]byte, []int) {
	return file_emails_v1_emails_proto_rawDescGZIP(), []int{0}
}

func (x *EmailReq) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *EmailReq) GetFromType() ContactType {
	if x != nil {
		return x.FromType
	}
	return ContactType_CONTACT_TYPE_UNSPECIFIED
}

func (x *EmailReq) GetTos() []string {
	if x != nil {
		return x.Tos
	}
	return nil
}

func (x *EmailReq) GetToType() ContactType {
	if x != nil {
		return x.ToType
	}
	return ContactType_CONTACT_TYPE_UNSPECIFIED
}

func (x *EmailReq) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *EmailReq) GetTemplate() string {
	if x != nil && x.Template != nil {
		return *x.Template
	}
	return ""
}

func (x *EmailReq) GetTemplateFile() string {
	if x != nil && x.TemplateFile != nil {
		return *x.TemplateFile
	}
	return ""
}

func (x *EmailReq) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type SendEmailRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRes) Reset() {
	*x = SendEmailRes{}
	mi := &file_emails_v1_emails_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRes) ProtoMessage() {}

func (x *SendEmailRes) ProtoReflect() protoreflect.Message {
	mi := &file_emails_v1_emails_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRes.ProtoReflect.Descriptor instead.
func (*SendEmailRes) Descriptor() ([]byte, []int) {
	return file_emails_v1_emails_proto_rawDescGZIP(), []int{1}
}

func (x *SendEmailRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_emails_v1_emails_proto protoreflect.FileDescriptor

const file_emails_v1_emails_proto_rawDesc = "" +
	"\n" +
	"\x16emails/v1/emails.proto\x12\temails.v1\"\xac\x03\n" +
	"\bEmailReq\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x123\n" +
	"\tfrom_type\x18\x02 \x01(\x0e2\x16.emails.v1.ContactTypeR\bfromType\x12\x10\n" +
	"\x03tos\x18\x03 \x03(\tR\x03tos\x12/\n" +
	"\ato_type\x18\x04 \x01(\x0e2\x16.emails.v1.ContactTypeR\x06toType\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1f\n" +
	"\btemplate\x18\n" +
	" \x01(\tH\x00R\btemplate\x88\x01\x01\x12(\n" +
	"\rtemplate_file\x18\v \x01(\tH\x01R\ftemplateFile\x88\x01\x01\x12:\n" +
	"\aoptions\x18\f \x03(\v2 .emails.v1.EmailReq.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\v\n" +
	"\t_templateB\x10\n" +
	"\x0e_template_file\"$\n" +
	"\fSendEmailRes\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error*X\n" +
	"\vContactType\x12\x1c\n" +
	"\x18CONTACT_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCONTACT_TYPE_ID\x10\x01\x12\x16\n" +
	"\x12CONTACT_TYPE_EMAIL\x10\x022K\n" +
	"\fEmailService\x12;\n" +
	"\tSendEmail\x12\x13.emails.v1.EmailReq\x1a\x17.emails.v1.SendEmailRes\"\x00B/Z-github.com/absmach/supermq/api/grpc/emails/v1b\x06proto3"

var (
	file_emails_v1_emails_proto_rawDescOnce sync.Once
	file_emails_v1_emails_proto_rawDescData []byte
)

func file_emails_v1_emails_proto_rawDescGZIP() []byte {
	file_emails_v1_emails_proto_rawDescOnce.Do(func() {
		file_emails_v1_emails_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_emails_v1_emails_proto_rawDesc), len(file_emails_v1_emails_proto_rawDesc)))
	})
	return file_emails_v1_emails_proto_rawDescData
}

var file_emails_v1_emails_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_emails_v1_emails_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_emails_v1_emails_proto_goTypes = []any{
	(ContactType)(0),     // 0: emails.v1.ContactType
	(*EmailReq)(nil),     // 1: emails.v1.EmailReq
	(*SendEmailRes)(nil), // 2: emails.v1.SendEmailRes
	nil,                  // 3: emails.v1.EmailReq.OptionsEntry
}
var file_emails_v1_emails_proto_depIdxs = []int32{
	0, // 0: emails.v1.EmailReq.from_type:type_name -> emails.v1.ContactType
	0, // 1: emails.v1.EmailReq.to_type:type_name -> emails.v1.ContactType
	3, // 2: emails.v1.EmailReq.options:type_name -> emails.v1.EmailReq.OptionsEntry
	1, // 3: emails.v1.EmailService.SendEmail:input_type -> emails.v1.EmailReq
	2, // 4: emails.v1.EmailService.SendEmail:output_type -> emails.v1.SendEmailRes
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_emails_v1_emails_proto_init() }
func file_emails_v1_emails_proto_init() {
	if File_emails_v1_emails_proto != nil {
		return
	}
	file_emails_v1_emails_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_emails_v1_emails_proto_rawDesc), len(file_emails_v1_emails_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_emails_v1_emails_proto_goTypes,
		DependencyIndexes: file_emails_v1_emails_proto_depIdxs,
		EnumInfos:         file_emails_v1_emails_proto_enumTypes,
		MessageInfos:      file_emails_v1_emails_proto_msgTypes,
	}.Build()
	File_emails_v1_emails_proto = out.File
	file_emails_v1_emails_proto_goTypes = nil
	file_emails_v1_emails_proto_depIdxs = nil
}
