// Copyright (c) Abstract Machines

// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	authn "github.com/absmach/supermq/pkg/authn"

	journal "github.com/absmach/supermq/journal"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// RetrieveAll provides a mock function with given fields: ctx, session, page
func (_m *Service) RetrieveAll(ctx context.Context, session authn.Session, page journal.Page) (journal.JournalsPage, error) {
	ret := _m.Called(ctx, session, page)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveAll")
	}

	var r0 journal.JournalsPage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, authn.Session, journal.Page) (journal.JournalsPage, error)); ok {
		return rf(ctx, session, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, authn.Session, journal.Page) journal.JournalsPage); ok {
		r0 = rf(ctx, session, page)
	} else {
		r0 = ret.Get(0).(journal.JournalsPage)
	}

	if rf, ok := ret.Get(1).(func(context.Context, authn.Session, journal.Page) error); ok {
		r1 = rf(ctx, session, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_RetrieveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveAll'
type Service_RetrieveAll_Call struct {
	*mock.Call
}

// RetrieveAll is a helper method to define mock.On call
//   - ctx context.Context
//   - session authn.Session
//   - page journal.Page
func (_e *Service_Expecter) RetrieveAll(ctx interface{}, session interface{}, page interface{}) *Service_RetrieveAll_Call {
	return &Service_RetrieveAll_Call{Call: _e.mock.On("RetrieveAll", ctx, session, page)}
}

func (_c *Service_RetrieveAll_Call) Run(run func(ctx context.Context, session authn.Session, page journal.Page)) *Service_RetrieveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(authn.Session), args[2].(journal.Page))
	})
	return _c
}

func (_c *Service_RetrieveAll_Call) Return(_a0 journal.JournalsPage, _a1 error) *Service_RetrieveAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_RetrieveAll_Call) RunAndReturn(run func(context.Context, authn.Session, journal.Page) (journal.JournalsPage, error)) *Service_RetrieveAll_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveClientTelemetry provides a mock function with given fields: ctx, session, clientID
func (_m *Service) RetrieveClientTelemetry(ctx context.Context, session authn.Session, clientID string) (journal.ClientTelemetry, error) {
	ret := _m.Called(ctx, session, clientID)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveClientTelemetry")
	}

	var r0 journal.ClientTelemetry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, authn.Session, string) (journal.ClientTelemetry, error)); ok {
		return rf(ctx, session, clientID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, authn.Session, string) journal.ClientTelemetry); ok {
		r0 = rf(ctx, session, clientID)
	} else {
		r0 = ret.Get(0).(journal.ClientTelemetry)
	}

	if rf, ok := ret.Get(1).(func(context.Context, authn.Session, string) error); ok {
		r1 = rf(ctx, session, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_RetrieveClientTelemetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveClientTelemetry'
type Service_RetrieveClientTelemetry_Call struct {
	*mock.Call
}

// RetrieveClientTelemetry is a helper method to define mock.On call
//   - ctx context.Context
//   - session authn.Session
//   - clientID string
func (_e *Service_Expecter) RetrieveClientTelemetry(ctx interface{}, session interface{}, clientID interface{}) *Service_RetrieveClientTelemetry_Call {
	return &Service_RetrieveClientTelemetry_Call{Call: _e.mock.On("RetrieveClientTelemetry", ctx, session, clientID)}
}

func (_c *Service_RetrieveClientTelemetry_Call) Run(run func(ctx context.Context, session authn.Session, clientID string)) *Service_RetrieveClientTelemetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(authn.Session), args[2].(string))
	})
	return _c
}

func (_c *Service_RetrieveClientTelemetry_Call) Return(_a0 journal.ClientTelemetry, _a1 error) *Service_RetrieveClientTelemetry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_RetrieveClientTelemetry_Call) RunAndReturn(run func(context.Context, authn.Session, string) (journal.ClientTelemetry, error)) *Service_RetrieveClientTelemetry_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, _a1
func (_m *Service) Save(ctx context.Context, _a1 journal.Journal) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, journal.Journal) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Service_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 journal.Journal
func (_e *Service_Expecter) Save(ctx interface{}, _a1 interface{}) *Service_Save_Call {
	return &Service_Save_Call{Call: _e.mock.On("Save", ctx, _a1)}
}

func (_c *Service_Save_Call) Run(run func(ctx context.Context, _a1 journal.Journal)) *Service_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(journal.Journal))
	})
	return _c
}

func (_c *Service_Save_Call) Return(_a0 error) *Service_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Save_Call) RunAndReturn(run func(context.Context, journal.Journal) error) *Service_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
